version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/adarsh
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=adarsh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A workers.celery_app worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/adarsh
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A workers.celery_app beat -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/adarsh
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - redis
      - postgres\n