version: '3.8'

services:
  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always

  redis:
    image: redis:7
    restart: always

  worker:
    build: .
    command: celery -A workers.celery_app worker -l info -Q default,imports,exports,images,notifications
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A workers.celery_app beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    depends_on:
      - redis
      - postgres\n