# Generated by Django 5.0.3 on 2026-06-03 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Table',
                'verbose_name_plural': 'Dynamic Tables',
            },
        ),
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('DOWNLOADED', 'Downloaded'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Stores dynamic fields matched with TableField.key')),
                ('images', models.JSONField(blank=True, default=dict, help_text="Maps image TableField.key -> {'original_path': '...', 'thumbnail_path': '...'}")),
                ('version', models.PositiveIntegerField(default=1, help_text='Used for optimistic concurrency checks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.dynamictable')),
            ],
            options={
                'verbose_name': 'Card Record',
                'verbose_name_plural': 'Card Records',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('IMPORT_XLSX', 'Create Table From Excel'), ('IMPORT_XLSX_ZIP', 'Import Data + Zip Images'), ('REUPLOAD_IMAGES', 'Bulk Zip Image Re-upload'), ('EXPORT_PDF', 'Export PDF Collection'), ('EXPORT_DOCX', 'Export Word Files'), ('EXPORT_XLSX', 'Export Data Excel'), ('EXPORT_ZIP', 'Export Card Zip Bundle')], max_length=30)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=15)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Task progress percentage (0-100)')),
                ('payload', models.JSONField(blank=True, default=dict, help_text="Task parameters. Example: {'table_id': '...', 'export_type': 'pdf'}")),
                ('result_url', models.URLField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=512)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.job')),
            ],
            options={
                'verbose_name': 'Job Log',
                'verbose_name_plural': 'Job Logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SandboxSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sandbox Session',
                'verbose_name_plural': 'Sandbox Sessions',
            },
        ),
        migrations.CreateModel(
            name='SandboxDelta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('delta_data', models.JSONField(blank=True, default=dict, help_text='Key-value modifications to merge into CardRecord.data on commit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cardrecord')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dynamictable')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='core.sandboxsession')),
            ],
            options={
                'verbose_name': 'Sandbox Delta',
                'verbose_name_plural': 'Sandbox Deltas',
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly column name (e.g. Employee ID)', max_length=255)),
                ('key', models.CharField(help_text='Database key stored in the jsonb field (e.g. employee_id)', max_length=63, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', message='Key must be alphanumeric and snake_case.')])),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('IMAGE', 'Image'), ('SELECT', 'Dropdown Select'), ('BOOLEAN', 'Boolean')], max_length=15)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Configuration values like select choices: {'choices': ['A', 'B']}, min/max validators")),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Index order for UI grid display')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.dynamictable')),
            ],
            options={
                'verbose_name': 'Table Field',
                'verbose_name_plural': 'Table Fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]+$', message='Subdomain must be lowercase alphanumeric characters or hyphens.')])),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text="JSON mapping of enabled platform features: {'max_tables': 10, 'exports_enabled': true}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'indexes': [models.Index(fields=['subdomain'], name='core_tenant_subdoma_5ebe44_idx')],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=63)),
                ('target_model', models.CharField(max_length=63)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Log attributes excluding credentials')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('impersonator', models.ForeignKey(blank=True, help_text='PRO_USER acting on behalf of the organization user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRO_USER', 'System Super Admin'), ('ADMIN', 'Organization Admin'), ('OPERATOR', 'Assigned Operator'), ('CLIENT', 'Organization Owner'), ('ASSISTANT', 'Client Assistant'), ('GUEST', 'Guest Sandbox User')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, help_text='Hierarchical supervisor: ADMIN manages OPERATORs, CLIENT manages ASSISTANTs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to='core.userprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operator_assignments', to='core.userprofile')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='core.userprofile')),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Operator Assignment',
                'verbose_name_plural': 'Operator Assignments',
            },
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.cardrecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Log',
                'verbose_name_plural': 'Workflow Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardrecord',
            index=models.Index(fields=['table', 'status'], name='core_cardre_table_i_cd7daf_idx'),
        ),
        migrations.AddIndex(
            model_name='cardrecord',
            index=models.Index(fields=['data'], name='card_record_data_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['user', 'is_active'], name='core_sandbo_user_id_d9c62c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablefield',
            unique_together={('table', 'key')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'status'], name='core_job_tenant__c2daf4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action'], name='core_auditl_tenant__f59c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='core_auditl_target__315580_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant', 'role'], name='core_userpr_tenant__4a5e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['managed_by'], name='core_userpr_managed_469004_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorassignment',
            index=models.Index(fields=['operator', 'client'], name='core_operat_operato_cdcfd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorassignment',
            unique_together={('operator', 'client')},
        ),
        migrations.AddIndex(
            model_name='dynamictable',
            index=models.Index(fields=['tenant', 'slug'], name='core_dynami_tenant__aea82a_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamictable',
            index=models.Index(fields=['client'], name='core_dynami_client__7a90ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamictable',
            unique_together={('tenant', 'slug')},
        ),
    ]
