# Generated by Django 5.0.3 on 2026-06-03 13:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(help_text='Key name in snake_case (e.g. advanced_reports)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
            },
        ),
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_code', models.CharField(help_text='e.g. 1.2.74', max_length=32, unique=True)),
                ('release_type', models.CharField(choices=[('STABLE', 'Stable Build'), ('BETA', 'Beta Preview'), ('HOTFIX', 'Hotfix Patch')], default='STABLE', max_length=15)),
                ('changelog', models.TextField()),
                ('min_desktop_version', models.CharField(default='1.0.0', max_length=32)),
                ('min_mobile_version', models.CharField(default='1.0.0', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Software Release',
                'verbose_name_plural': 'Software Releases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesktopDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_identifier', models.CharField(help_text='Unique hardware GUID hash', max_length=255, unique=True)),
                ('os_platform', models.CharField(max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_devices', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desktop Device',
                'verbose_name_plural': 'Desktop Devices',
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=1024)),
                ('event_subscriptions', models.JSONField(default=list, help_text="E.g. ['card.created', 'card.deleted', 'export.ready']")),
                ('secret_token', models.CharField(help_text='HMAC key token signing post payloads', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Integration Webhook',
                'verbose_name_plural': 'Integration Webhooks',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='In bytes')),
                ('mime_type', models.CharField(max_length=127)),
                ('storage_path', models.CharField(help_text='Relative storage driver locator path', max_length=512)),
                ('public_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INIT', 'Initialized'), ('UPLOADED', 'Spreadsheet Uploaded'), ('VALIDATING', 'Running Verification checks'), ('MERGING', 'Applying items to Database'), ('COMPLETED', 'Finished Successfully'), ('FAILED', 'Operation Terminated with errors')], default='INIT', max_length=15)),
                ('mapping_config', models.JSONField(blank=True, default=dict, help_text='Maps headers to field snake_case keys')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='core.dynamictable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xlsx_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xlsx_imports', to='core.mediafile')),
                ('zip_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_imports', to='core.mediafile')),
            ],
            options={
                'verbose_name': 'Import Session',
                'verbose_name_plural': 'Import Sessions',
            },
        ),
        migrations.CreateModel(
            name='ExportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('PDF', 'PDF Print Document'), ('DOCX', 'Word Layout Template'), ('XLSX', 'Excel Table Grid'), ('ZIP', 'Images Bundle Package')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending generation'), ('PROCESSING', 'Exporting assets'), ('COMPLETED', 'Upload complete'), ('FAILED', 'Generation failed')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_sessions', to='core.dynamictable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_sessions', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='core.mediafile')),
            ],
            options={
                'verbose_name': 'Export Session',
                'verbose_name_plural': 'Export Sessions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System Message'), ('EXPORT_READY', 'Document Export Ready'), ('IMPORT_COMPLETE', 'Import Pipeline Complete'), ('SECURITY_ALERT', 'Security Notification')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('query_json', models.JSONField(help_text='Serialized representation of search criteria and sorting rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='core.dynamictable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search Query',
                'verbose_name_plural': 'Saved Search Queries',
            },
        ),
        migrations.CreateModel(
            name='SyncChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField()),
                ('change_type', models.CharField(choices=[('INSERT', 'Create Row'), ('UPDATE', 'Modify Row'), ('DELETE', 'Soft Delete Row')], max_length=10)),
                ('version', models.PositiveIntegerField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_changelogs', to='core.dynamictable')),
            ],
            options={
                'verbose_name': 'Sync Change Log',
                'verbose_name_plural': 'Sync Change Logs',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list, help_text='List of permitted CIDR blocks')),
                ('password_policy', models.JSONField(blank=True, default=dict, help_text="Rules parameters: {'min_length': 8, 'require_uppercase': true}")),
                ('session_timeout_seconds', models.PositiveIntegerField(default=3600)),
                ('custom_branding', models.JSONField(blank=True, default=dict, help_text="Styling themes: {'primary_color': '#4A90E2', 'logo_url': '...'}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='TableTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fields_schema', models.JSONField(help_text='Serialized TableField array structure defining properties list')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Table Template',
                'verbose_name_plural': 'Table Templates',
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config_override', models.JSONField(blank=True, default=dict, help_text='Custom settings overlay for this tenant')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='core.featureflag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Feature Override',
                'verbose_name_plural': 'Tenant Feature Overrides',
            },
        ),
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('BULK_DELETE', 'Bulk Delete Cards'), ('BULK_STATUS_CHANGE', 'Bulk Status Updates'), ('BULK_FIELD_UPDATE', 'Bulk Edit Fields')], max_length=25)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Worker Execution'), ('RUNNING', 'Running'), ('COMPLETED', 'Finished Successfully'), ('FAILED', 'Failed execution')], default='PENDING', max_length=15)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Filter query, update parameters, or targets IDs')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Operation',
                'verbose_name_plural': 'Bulk Operations',
                'indexes': [models.Index(fields=['tenant', 'status'], name='core_bulkop_tenant__d5a604_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(help_text='Detailed event data payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='core_eventl_tenant__55ffff_idx'), models.Index(fields=['payload'], name='event_log_payload_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('impersonated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
                ('impersonator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonation Session',
                'verbose_name_plural': 'Impersonation Sessions',
                'indexes': [models.Index(fields=['impersonator', 'ended_at'], name='core_impers_imperso_f07227_idx')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic Edition'), ('PREMIUM', 'Premium Edition'), ('ENTERPRISE', 'Enterprise Edition')], default='BASIC', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_tables', models.PositiveIntegerField(default=3)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('cryptographic_signature', models.CharField(help_text='Sha256 hash hash signature validating payload to prevent manual db tampering', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='core.tenant')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='core_licens_tenant__5ce10a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['tenant', 'mime_type'], name='core_mediaf_tenant__c468b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsearchquery',
            unique_together={('user', 'table', 'name')},
        ),
        migrations.AddIndex(
            model_name='syncchangelog',
            index=models.Index(fields=['table', 'modified_at'], name='core_syncch_table_i_52c05b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureoverride',
            index=models.Index(fields=['tenant', 'feature'], name='core_tenant_tenant__664415_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantfeatureoverride',
            unique_together={('tenant', 'feature')},
        ),
    ]
